<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="DESKTOP-PG39M5C" name="practice.sdet31.testNgPractice.CreateOrganiaztionTest" tests="2" failures="0" timestamp="2022-03-29T14:16:04 IST" time="127.789" errors="0">
  <testcase name="createOrganization" time="107.023" classname="practice.sdet31.testNgPractice.CreateOrganiaztionTest"/>
  <system-out/>
  <testcase name="exception" time="20.766" classname="practice.sdet31.testNgPractice.CreateOrganiaztionTest">
    <skipped/>
  </testcase> <!-- exception -->
  <system-out/>
</testsuite> <!-- practice.sdet31.testNgPractice.CreateOrganiaztionTest -->
